# ----------------------------------------- 
# Template for a configuration file used in 
# automatic deployments and commit checks
# ----------------------------------------- 

# ----------------------------------------- 
# General settings for the current folder
# ----------------------------------------- 

### KeepEmptyFolder
# Values: true, false
# Usage: optional, default is false
#
# Folder without any files files are not
# written to the tarball. Set this to true,
# if you want to retain the directory, even
# if it contains no files (or folders)
#
# Example:
# KeepEmptyFolder = true

### ValidChars
# Values: "All", 
#         "Ascii", 
#         "AsciiGerman", 
#         "Ascii + {others}", 
#         "AsciiGerman (+ OtherChars)"
# Usage: optional, default is "AsciiGerman"
# 
# Encoding problems lead to mangled and 
# unexpected characters in source files.
# This property sets a default for the 
# valid characters in the folder's files.
# All: turns off all checks
# Ascii: Allows only the 128 characters
#        defined in the ASCII standard
# AsciiGerman: Builds on Ascii and adds
#              the chars äöüÄÖÜß€
# You can extend Ascii and AsciiGerman
# by putting the additional characters
# after the name and a plus sign.
#
# Example: (needed by db\build\DANET\PackageBodies\pba_events.sql)
# ValidChars = "AsciiGerman + ¿§"


# ----------------------------------------- 
# Filter and transformaton rules for the
# files in the current directory
# ----------------------------------------- 

### Rules sections
# Values: Each [[Rules]] line, starts a 
#         new filter and transformation
#         rule
# Usage: optional. There is always a final 
#        rule added to the list, which 
#        just copies the files unchanged 
#        to the tarball. So if no rules
#        are defined, this rule will be
#        applied.
# 
# Rules are applied in the order that
# they appear in the configuration. So 
# you can priorize rules by putting them
# towards the beginning of the file.
#
# Example:
#
# [[Rules]]
# Action = "copy"
# WhenNameIsEqual = "auskunft.config"
#
# [[Rules]]
# Action = "skip"
# 
# This rule sequence will match the 
# file auskunft.config and copy it with
# default settings to the tarball. All
# other files are handled by the skip 
# rules and will not be copied to the
# tarball. The implicit default rule
# never gets executed, because the 
# skip rule handles everthing.

# ----------------------------------------- 
# Content of a filter and transformaton rule
# ----------------------------------------- 


### ValidChars
# Values: "All", 
#         "Ascii", 
#         "AsciiGerman", 
#         "Ascii + {others}", 
#         "AsciiGerman (+ OtherChars)"
# Usage: optional, default is "AsciiGerman"
# 
# Encoding problems lead to mangled and 
# unexpected characters in source files.
# This property sets a default for the 
# valid characters in the folder's files.
# All: turns off all checks
# Ascii: Allows only the 128 characters
#        defined in the ASCII standard
# AsciiGerman: Builds on Ascii and adds
#              the chars äöüÄÖÜß€
# You can extend Ascii and AsciiGerman
# by putting the additional characters
# after the name and a plus sign.
#
# Example: (needed by db\build\DANET\PackageBodies\pba_events.sql)
# ValidChars = "AsciiGerman + ¿§"

Action = "copy"
WhenNameIsEqual = "auskunft.config"

[[Rules]]
Action = "copy"
WhenNameMatchesPattern = "load*"

[[Rules]]
Action = "skip"


