### YamlMime:ManagedReference
items:
- uid: vigocfg.IStagingEnvironment
  commentId: T:vigocfg.IStagingEnvironment
  id: IStagingEnvironment
  parent: vigocfg
  children:
  - vigocfg.IStagingEnvironment.Key
  - vigocfg.IStagingEnvironment.Name
  langs:
  - csharp
  - vb
  name: IStagingEnvironment
  nameWithType: IStagingEnvironment
  fullName: vigocfg.IStagingEnvironment
  type: Interface
  source:
    remote:
      path: src/vigocfg/IVigoConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: IStagingEnvironment
    path: ../src/vigocfg/IVigoConfig.cs
    startLine: 11
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: public interface IStagingEnvironment
    content.vb: Public Interface IStagingEnvironment
- uid: vigocfg.IStagingEnvironment.Key
  commentId: P:vigocfg.IStagingEnvironment.Key
  id: Key
  parent: vigocfg.IStagingEnvironment
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: IStagingEnvironment.Key
  fullName: vigocfg.IStagingEnvironment.Key
  type: Property
  source:
    remote:
      path: src/vigocfg/IVigoConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Key
    path: ../src/vigocfg/IVigoConfig.cs
    startLine: 13
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: string Key { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Key As String
  overload: vigocfg.IStagingEnvironment.Key*
- uid: vigocfg.IStagingEnvironment.Name
  commentId: P:vigocfg.IStagingEnvironment.Name
  id: Name
  parent: vigocfg.IStagingEnvironment
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IStagingEnvironment.Name
  fullName: vigocfg.IStagingEnvironment.Name
  type: Property
  source:
    remote:
      path: src/vigocfg/IVigoConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Name
    path: ../src/vigocfg/IVigoConfig.cs
    startLine: 14
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: vigocfg.IStagingEnvironment.Name*
references:
- uid: vigocfg
  commentId: N:vigocfg
  href: vigocfg.html
  name: vigocfg
  nameWithType: vigocfg
  fullName: vigocfg
- uid: vigocfg.IStagingEnvironment.Key*
  commentId: Overload:vigocfg.IStagingEnvironment.Key
  href: vigocfg.IStagingEnvironment.html#vigocfg_IStagingEnvironment_Key
  name: Key
  nameWithType: IStagingEnvironment.Key
  fullName: vigocfg.IStagingEnvironment.Key
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: vigocfg.IStagingEnvironment.Name*
  commentId: Overload:vigocfg.IStagingEnvironment.Name
  href: vigocfg.IStagingEnvironment.html#vigocfg_IStagingEnvironment_Name
  name: Name
  nameWithType: IStagingEnvironment.Name
  fullName: vigocfg.IStagingEnvironment.Name
