### YamlMime:ManagedReference
items:
- uid: vigocfg.StagingEnvironmentEnum
  commentId: T:vigocfg.StagingEnvironmentEnum
  id: StagingEnvironmentEnum
  parent: vigocfg
  children:
  - vigocfg.StagingEnvironmentEnum.ContinuousIntegrationAndTest
  - vigocfg.StagingEnvironmentEnum.Development
  - vigocfg.StagingEnvironmentEnum.Production
  - vigocfg.StagingEnvironmentEnum.Reference
  - vigocfg.StagingEnvironmentEnum.Undefined
  - vigocfg.StagingEnvironmentEnum.UserAcceptanceTest
  langs:
  - csharp
  - vb
  name: StagingEnvironmentEnum
  nameWithType: StagingEnvironmentEnum
  fullName: vigocfg.StagingEnvironmentEnum
  type: Enum
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: StagingEnvironmentEnum
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 2
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: public enum StagingEnvironmentEnum
    content.vb: Public Enum StagingEnvironmentEnum
  extensionMethods:
  - vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.IsDefined
  - vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid
  - vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.Key
  - vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.Name
- uid: vigocfg.StagingEnvironmentEnum.Undefined
  commentId: F:vigocfg.StagingEnvironmentEnum.Undefined
  id: Undefined
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: Undefined
  nameWithType: StagingEnvironmentEnum.Undefined
  fullName: vigocfg.StagingEnvironmentEnum.Undefined
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Undefined
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 4
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: Undefined = 0
    return:
      type: vigocfg.StagingEnvironmentEnum
- uid: vigocfg.StagingEnvironmentEnum.Development
  commentId: F:vigocfg.StagingEnvironmentEnum.Development
  id: Development
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: Development
  nameWithType: StagingEnvironmentEnum.Development
  fullName: vigocfg.StagingEnvironmentEnum.Development
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Development
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 5
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: Development = 1
    return:
      type: vigocfg.StagingEnvironmentEnum
- uid: vigocfg.StagingEnvironmentEnum.ContinuousIntegrationAndTest
  commentId: F:vigocfg.StagingEnvironmentEnum.ContinuousIntegrationAndTest
  id: ContinuousIntegrationAndTest
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: ContinuousIntegrationAndTest
  nameWithType: StagingEnvironmentEnum.ContinuousIntegrationAndTest
  fullName: vigocfg.StagingEnvironmentEnum.ContinuousIntegrationAndTest
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: ContinuousIntegrationAndTest
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 6
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: ContinuousIntegrationAndTest = 2
    return:
      type: vigocfg.StagingEnvironmentEnum
- uid: vigocfg.StagingEnvironmentEnum.UserAcceptanceTest
  commentId: F:vigocfg.StagingEnvironmentEnum.UserAcceptanceTest
  id: UserAcceptanceTest
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: UserAcceptanceTest
  nameWithType: StagingEnvironmentEnum.UserAcceptanceTest
  fullName: vigocfg.StagingEnvironmentEnum.UserAcceptanceTest
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: UserAcceptanceTest
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 7
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: UserAcceptanceTest = 3
    return:
      type: vigocfg.StagingEnvironmentEnum
- uid: vigocfg.StagingEnvironmentEnum.Reference
  commentId: F:vigocfg.StagingEnvironmentEnum.Reference
  id: Reference
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: Reference
  nameWithType: StagingEnvironmentEnum.Reference
  fullName: vigocfg.StagingEnvironmentEnum.Reference
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Reference
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 8
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: Reference = 4
    return:
      type: vigocfg.StagingEnvironmentEnum
- uid: vigocfg.StagingEnvironmentEnum.Production
  commentId: F:vigocfg.StagingEnvironmentEnum.Production
  id: Production
  parent: vigocfg.StagingEnvironmentEnum
  langs:
  - csharp
  - vb
  name: Production
  nameWithType: StagingEnvironmentEnum.Production
  fullName: vigocfg.StagingEnvironmentEnum.Production
  type: Field
  source:
    remote:
      path: src/vigocfg/StagingEnvironmentEnum.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: Production
    path: ../src/vigocfg/StagingEnvironmentEnum.cs
    startLine: 9
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: Production = 5
    return:
      type: vigocfg.StagingEnvironmentEnum
references:
- uid: vigocfg
  commentId: N:vigocfg
  href: vigocfg.html
  name: vigocfg
  nameWithType: vigocfg
  fullName: vigocfg
- uid: vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.IsDefined
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  parent: vigocfg.StagingEnvironmentEnumHelper
  definition: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  name: IsDefined(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.IsDefined(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
    name: IsDefined
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
    name: IsDefined
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  parent: vigocfg.StagingEnvironmentEnumHelper
  definition: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  name: IsDefinedAndValid(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.IsDefinedAndValid(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
    name: IsDefinedAndValid
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
    name: IsDefinedAndValid
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.Key
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  parent: vigocfg.StagingEnvironmentEnumHelper
  definition: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  name: Key(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.Key(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
    name: Key
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
    name: Key
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnum.vigocfg.StagingEnvironmentEnumHelper.Name
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  parent: vigocfg.StagingEnvironmentEnumHelper
  definition: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  name: Name(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.Name(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
    name: Name
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
    name: Name
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  name: IsDefined(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.IsDefined(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
    name: IsDefined
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefined(vigocfg.StagingEnvironmentEnum)
    name: IsDefined
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefined_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnumHelper
  commentId: T:vigocfg.StagingEnvironmentEnumHelper
  parent: vigocfg
  href: vigocfg.StagingEnvironmentEnumHelper.html
  name: StagingEnvironmentEnumHelper
  nameWithType: StagingEnvironmentEnumHelper
  fullName: vigocfg.StagingEnvironmentEnumHelper
- uid: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  name: IsDefinedAndValid(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.IsDefinedAndValid(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
    name: IsDefinedAndValid
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.IsDefinedAndValid(vigocfg.StagingEnvironmentEnum)
    name: IsDefinedAndValid
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_IsDefinedAndValid_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  name: Key(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.Key(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
    name: Key
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Key(vigocfg.StagingEnvironmentEnum)
    name: Key
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Key_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  commentId: M:vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  name: Name(StagingEnvironmentEnum)
  nameWithType: StagingEnvironmentEnumHelper.Name(StagingEnvironmentEnum)
  fullName: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
  spec.csharp:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
    name: Name
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
  spec.vb:
  - uid: vigocfg.StagingEnvironmentEnumHelper.Name(vigocfg.StagingEnvironmentEnum)
    name: Name
    href: vigocfg.StagingEnvironmentEnumHelper.html#vigocfg_StagingEnvironmentEnumHelper_Name_vigocfg_StagingEnvironmentEnum_
  - name: (
  - uid: vigocfg.StagingEnvironmentEnum
    name: StagingEnvironmentEnum
    href: vigocfg.StagingEnvironmentEnum.html
  - name: )
- uid: vigocfg.StagingEnvironmentEnum
  commentId: T:vigocfg.StagingEnvironmentEnum
  parent: vigocfg
  href: vigocfg.StagingEnvironmentEnum.html
  name: StagingEnvironmentEnum
  nameWithType: StagingEnvironmentEnum
  fullName: vigocfg.StagingEnvironmentEnum
