### YamlMime:ManagedReference
items:
- uid: vigocfg.INameParserConfig
  commentId: T:vigocfg.INameParserConfig
  id: INameParserConfig
  parent: vigocfg
  children:
  - vigocfg.INameParserConfig.CaseInsensitiveFilterTags
  - vigocfg.INameParserConfig.CaseSensitiveFilterTags
  langs:
  - csharp
  - vb
  name: INameParserConfig
  nameWithType: INameParserConfig
  fullName: vigocfg.INameParserConfig
  type: Interface
  source:
    remote:
      path: src/vigocfg/INameParserConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: INameParserConfig
    path: ../src/vigocfg/INameParserConfig.cs
    startLine: 2
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: public interface INameParserConfig
    content.vb: Public Interface INameParserConfig
- uid: vigocfg.INameParserConfig.CaseSensitiveFilterTags
  commentId: P:vigocfg.INameParserConfig.CaseSensitiveFilterTags
  id: CaseSensitiveFilterTags
  parent: vigocfg.INameParserConfig
  langs:
  - csharp
  - vb
  name: CaseSensitiveFilterTags
  nameWithType: INameParserConfig.CaseSensitiveFilterTags
  fullName: vigocfg.INameParserConfig.CaseSensitiveFilterTags
  type: Property
  source:
    remote:
      path: src/vigocfg/INameParserConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: CaseSensitiveFilterTags
    path: ../src/vigocfg/INameParserConfig.cs
    startLine: 4
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: IEnumerable<string> CaseSensitiveFilterTags { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.String}
    content.vb: ReadOnly Property CaseSensitiveFilterTags As IEnumerable(Of String)
  overload: vigocfg.INameParserConfig.CaseSensitiveFilterTags*
- uid: vigocfg.INameParserConfig.CaseInsensitiveFilterTags
  commentId: P:vigocfg.INameParserConfig.CaseInsensitiveFilterTags
  id: CaseInsensitiveFilterTags
  parent: vigocfg.INameParserConfig
  langs:
  - csharp
  - vb
  name: CaseInsensitiveFilterTags
  nameWithType: INameParserConfig.CaseInsensitiveFilterTags
  fullName: vigocfg.INameParserConfig.CaseInsensitiveFilterTags
  type: Property
  source:
    remote:
      path: src/vigocfg/INameParserConfig.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: CaseInsensitiveFilterTags
    path: ../src/vigocfg/INameParserConfig.cs
    startLine: 5
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: IEnumerable<string> CaseInsensitiveFilterTags { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.String}
    content.vb: ReadOnly Property CaseInsensitiveFilterTags As IEnumerable(Of String)
  overload: vigocfg.INameParserConfig.CaseInsensitiveFilterTags*
references:
- uid: vigocfg
  commentId: N:vigocfg
  href: vigocfg.html
  name: vigocfg
  nameWithType: vigocfg
  fullName: vigocfg
- uid: vigocfg.INameParserConfig.CaseSensitiveFilterTags*
  commentId: Overload:vigocfg.INameParserConfig.CaseSensitiveFilterTags
  href: vigocfg.INameParserConfig.html#vigocfg_INameParserConfig_CaseSensitiveFilterTags
  name: CaseSensitiveFilterTags
  nameWithType: INameParserConfig.CaseSensitiveFilterTags
  fullName: vigocfg.INameParserConfig.CaseSensitiveFilterTags
- uid: System.Collections.Generic.IEnumerable{System.String}
  commentId: T:System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<string>
  nameWithType: IEnumerable<string>
  fullName: System.Collections.Generic.IEnumerable<string>
  nameWithType.vb: IEnumerable(Of String)
  fullName.vb: System.Collections.Generic.IEnumerable(Of String)
  name.vb: IEnumerable(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: vigocfg.INameParserConfig.CaseInsensitiveFilterTags*
  commentId: Overload:vigocfg.INameParserConfig.CaseInsensitiveFilterTags
  href: vigocfg.INameParserConfig.html#vigocfg_INameParserConfig_CaseInsensitiveFilterTags
  name: CaseInsensitiveFilterTags
  nameWithType: INameParserConfig.CaseInsensitiveFilterTags
  fullName: vigocfg.INameParserConfig.CaseInsensitiveFilterTags
