### YamlMime:ManagedReference
items:
- uid: vigocfg.IFileSystemEnvironment
  commentId: T:vigocfg.IFileSystemEnvironment
  id: IFileSystemEnvironment
  parent: vigocfg
  children:
  - vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
  - vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
  - vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
  - vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
  - vigocfg.IFileSystemEnvironment.TargetFolderCupines
  - vigocfg.IFileSystemEnvironment.TargetFolderFlyway
  - vigocfg.IFileSystemEnvironment.TargetFolderStammaus
  langs:
  - csharp
  - vb
  name: IFileSystemEnvironment
  nameWithType: IFileSystemEnvironment
  fullName: vigocfg.IFileSystemEnvironment
  type: Interface
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: IFileSystemEnvironment
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 2
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: public interface IFileSystemEnvironment
    content.vb: Public Interface IFileSystemEnvironment
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
  commentId: P:vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
  id: SourceRepositoryRoot
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: SourceRepositoryRoot
  nameWithType: IFileSystemEnvironment.SourceRepositoryRoot
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: SourceRepositoryRoot
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 4
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo SourceRepositoryRoot { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property SourceRepositoryRoot As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.SourceRepositoryRoot*
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
  commentId: P:vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
  id: SourceRepositoryFlyway
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: SourceRepositoryFlyway
  nameWithType: IFileSystemEnvironment.SourceRepositoryFlyway
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: SourceRepositoryFlyway
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 5
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo SourceRepositoryFlyway { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property SourceRepositoryFlyway As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway*
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
  commentId: P:vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
  id: SourceRepositoryStammaus
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: SourceRepositoryStammaus
  nameWithType: IFileSystemEnvironment.SourceRepositoryStammaus
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: SourceRepositoryStammaus
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 6
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo SourceRepositoryStammaus { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property SourceRepositoryStammaus As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus*
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
  commentId: P:vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
  id: SourceRepositoryCupines
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: SourceRepositoryCupines
  nameWithType: IFileSystemEnvironment.SourceRepositoryCupines
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: SourceRepositoryCupines
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 7
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo SourceRepositoryCupines { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property SourceRepositoryCupines As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.SourceRepositoryCupines*
- uid: vigocfg.IFileSystemEnvironment.TargetFolderFlyway
  commentId: P:vigocfg.IFileSystemEnvironment.TargetFolderFlyway
  id: TargetFolderFlyway
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: TargetFolderFlyway
  nameWithType: IFileSystemEnvironment.TargetFolderFlyway
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderFlyway
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: TargetFolderFlyway
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 8
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo? TargetFolderFlyway { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property TargetFolderFlyway As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.TargetFolderFlyway*
- uid: vigocfg.IFileSystemEnvironment.TargetFolderStammaus
  commentId: P:vigocfg.IFileSystemEnvironment.TargetFolderStammaus
  id: TargetFolderStammaus
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: TargetFolderStammaus
  nameWithType: IFileSystemEnvironment.TargetFolderStammaus
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderStammaus
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: TargetFolderStammaus
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 9
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo? TargetFolderStammaus { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property TargetFolderStammaus As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.TargetFolderStammaus*
- uid: vigocfg.IFileSystemEnvironment.TargetFolderCupines
  commentId: P:vigocfg.IFileSystemEnvironment.TargetFolderCupines
  id: TargetFolderCupines
  parent: vigocfg.IFileSystemEnvironment
  langs:
  - csharp
  - vb
  name: TargetFolderCupines
  nameWithType: IFileSystemEnvironment.TargetFolderCupines
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderCupines
  type: Property
  source:
    remote:
      path: src/vigocfg/IFileSystemEnvironment.cs
      branch: main
      repo: https://git.dhl.com/b7o1tue0137/vigo.git
    id: TargetFolderCupines
    path: ../src/vigocfg/IFileSystemEnvironment.cs
    startLine: 10
  assemblies:
  - vigocfg
  namespace: vigocfg
  syntax:
    content: DirectoryInfo? TargetFolderCupines { get; }
    parameters: []
    return:
      type: System.IO.DirectoryInfo
    content.vb: ReadOnly Property TargetFolderCupines As DirectoryInfo
  overload: vigocfg.IFileSystemEnvironment.TargetFolderCupines*
references:
- uid: vigocfg
  commentId: N:vigocfg
  href: vigocfg.html
  name: vigocfg
  nameWithType: vigocfg
  fullName: vigocfg
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryRoot*
  commentId: Overload:vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_SourceRepositoryRoot
  name: SourceRepositoryRoot
  nameWithType: IFileSystemEnvironment.SourceRepositoryRoot
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryRoot
- uid: System.IO.DirectoryInfo
  commentId: T:System.IO.DirectoryInfo
  parent: System.IO
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.io.directoryinfo
  name: DirectoryInfo
  nameWithType: DirectoryInfo
  fullName: System.IO.DirectoryInfo
- uid: System.IO
  commentId: N:System.IO
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.IO
    name: IO
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.IO
    name: IO
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway*
  commentId: Overload:vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_SourceRepositoryFlyway
  name: SourceRepositoryFlyway
  nameWithType: IFileSystemEnvironment.SourceRepositoryFlyway
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryFlyway
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus*
  commentId: Overload:vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_SourceRepositoryStammaus
  name: SourceRepositoryStammaus
  nameWithType: IFileSystemEnvironment.SourceRepositoryStammaus
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryStammaus
- uid: vigocfg.IFileSystemEnvironment.SourceRepositoryCupines*
  commentId: Overload:vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_SourceRepositoryCupines
  name: SourceRepositoryCupines
  nameWithType: IFileSystemEnvironment.SourceRepositoryCupines
  fullName: vigocfg.IFileSystemEnvironment.SourceRepositoryCupines
- uid: vigocfg.IFileSystemEnvironment.TargetFolderFlyway*
  commentId: Overload:vigocfg.IFileSystemEnvironment.TargetFolderFlyway
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_TargetFolderFlyway
  name: TargetFolderFlyway
  nameWithType: IFileSystemEnvironment.TargetFolderFlyway
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderFlyway
- uid: vigocfg.IFileSystemEnvironment.TargetFolderStammaus*
  commentId: Overload:vigocfg.IFileSystemEnvironment.TargetFolderStammaus
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_TargetFolderStammaus
  name: TargetFolderStammaus
  nameWithType: IFileSystemEnvironment.TargetFolderStammaus
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderStammaus
- uid: vigocfg.IFileSystemEnvironment.TargetFolderCupines*
  commentId: Overload:vigocfg.IFileSystemEnvironment.TargetFolderCupines
  href: vigocfg.IFileSystemEnvironment.html#vigocfg_IFileSystemEnvironment_TargetFolderCupines
  name: TargetFolderCupines
  nameWithType: IFileSystemEnvironment.TargetFolderCupines
  fullName: vigocfg.IFileSystemEnvironment.TargetFolderCupines
